### ISSUE TITLE
Start mining after calibration + don't exit on unstable hashrates

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#10]
Currently, if hashrates doesn't stabilize after x minutes, minotaur exits calibration mode. 

Some algorithms(miners?) has very unstable hashrates, making it hard to do a complete calibration for all algos/miners, without checking the rig all the time, if it might have stopped. 

Would be nice if it would just skip the algo/miner and proceed to the next.

An option to start mining after completing calibration would also be nice!

**Comment by m4rkw** [comment]
ive just pushed a change to master so it no longer exits when it doesn't get a stable hashrate, so if you've asked it to calibrate more than one algo it will continue.

to mine after calibration, you can first start mining as normal across all of your devices, then run calibration with --force.  minotaur will ignore the devices until they've finished calibrating and then start mining with them when they're done.
