### ISSUE TITLE
Log rotation and --stats

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#15]
I was unable to get stats for more than a period of a couple of hours and found that the reason is because of log rotation.

When log rotation is applied (`minotaur.csv` becomes `minotaur.csv.1`) and `minotaur --stats` will only read values from `minotaur.log`.

**Comment by gordan-bobic** [comment]
This is normal and expected. These logs are intended for importing into a spreadsheet for any further analysis.
