### ISSUE TITLE
minotaur --gs doesn't work in terminal on iPhone

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#18]
I'm using terminus: https://itunes.apple.com/us/app/termius/id549039908?mt=8

![image](https://user-images.githubusercontent.com/230182/36170761-975da09c-1100-11e8-8973-5b307fc42dbc.png)

**Comment by m4rkw** [comment]
try --gs --mobile   with 0.9.9.3

(rotate into landscape mode first or ncurses goes a bit weird)
