### ISSUE TITLE
Auto overclock

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#2]
Do you think it would be possible to implement auto overclocking, something along the lines of how power limit benchmark works?

**Comment by m4rkw** [comment]
Hi, whilst it might be possible, it isn't something I'd want the software to take responsibility for. If someone used such a feature and 3 months later their card stopped working they might blame me for it so I think it's better if overclocking remains entirely at the discretion and responsibility of the user.  I'm also not sure how Minotaur could accurately determine whether settings were "stable".  I've overclocked in the past and found that devices can seem completely stable until you run specific tests on them and then find weaknesses.  Given the complexity involved I think it's outside of the scope of what the software intends to do.

It does however support device profiles that you can configure per-device and even per-algorithm if you want to customise your oc settings to that degree.
