### ISSUE TITLE
Add support for MiningPoolHub

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#21]
What do you think about adding support for [MiningPoolHub](https://miningpoolhub.com/)?

You can mine (and keep) a lot of different coins, and also has an option (via pool's website) to set if you want (some or all) mined coins auto-exchanged to a different coin.

Pool fee is 0.9%.

**Comment by m4rkw** [comment]
funnily enough i added this to the private backlog this morning :)  will look at it asap

**Comment by m4rkw** [comment]
done in 1.0
