### ISSUE TITLE
Power draw now stat seems fishy

### ISSUE THREAD

**Issue by markjca** [m4rkw/minotaur#27]
The power draw now stat seems a bit fishy since it is always much higher than the average. It may be that it is calculated differently from the others (like its a peak hold or something) but looking at the numbers you'd think that "5 min avg" would be the avg of all of the "power draw now" readings taken over the last 5 mins but that's definitely not the case. Is there something wrong here?

Below are more or less what my values have been reported as on the --gs screen for pretty much the past half hour.

```
 power draw now:    925 W 132.3%
     5 mins avg:    722 W 103.3%
    10 mins avg:    724 W 103.4%
    15 mins avg:    721 W 103.0%
        ins avg:    719 W 102.7%
```

**Comment by m4rkw** [comment]
The value for system_draw_watts in the config file was being applied to the "now" number but not the averages. This has been fixed in 1.1.1.  Set this to an appropriate value for your system and the averages will slowly come into line.  1.1.1 will be released later tonight.
