### ISSUE TITLE
--html and --gs discrepancy

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#28]
![image](https://user-images.githubusercontent.com/230182/36643973-6d6c0ce0-1a53-11e8-9d7e-42d1aeb0754a.png)

**Comment by biesbjerg** [comment]
`minotaur --mine` was running as `minotaur` and `minotaur --html` was running as `root` (to have permissions to write to /var/www/html. 

Not sure why the discrepancies, but almost certainly a permission problem.

**Comment by m4rkw** [comment]
protip: create /var/www/html/minotaur and chown it to minotaur:minotaur
