### ISSUE TITLE
Error on launche

### ISSUE THREAD

**Issue by stefanogalizia** [m4rkw/minotaur#4]
I tried to launch the package but i get this error:

./minotaur --quickstart
Traceback (most recent call last):
File "/home/miner/minotaur/minotaur.py", line 21, in 
File "/home/miner/minotaur/gs.py", line 18, in 
File "/usr/lib/python2.7/site-packages/paramiko/init.py", line 22, in 
File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 57, in 
File "/usr/lib/python2.7/site-packages/paramiko/ed25519key.py", line 17, in 
File "/usr/lib64/python2.7/site-packages/bcrypt/init.py", line 25, in 
ImportError: cannot import name '_bcrypt'

I installed the bcrypt package using the pip command.
Here is my linux version:
Linux miningrig1 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Any help?

**Comment by m4rkw** [comment]
what happens if you install paramiko?

sudo pip install paramiko

**Comment by stefanogalizia** [comment]
Installed 
"pip install paramiko
Collecting paramiko
  Downloading paramiko-2.4.0-py2.py3-none-any.whl (192kB)
    100% |████████████████████████████████| 194kB 1.2MB/s
Collecting pyasn1>=0.1.7 (from paramiko)
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 2.1MB/s
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko)
Collecting cryptography>=1.5 (from paramiko)
  Downloading cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 363kB/s
Collecting pynacl>=1.0.1 (from paramiko)
  Downloading PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (696kB)
    100% |████████████████████████████████| 706kB 751kB/s
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko)
Collecting enum34; python_version < "3" (from cryptography>=1.5->paramiko)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko)
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 677kB/s
Collecting idna>=2.1 (from cryptography>=1.5->paramiko)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.4MB/s
Collecting ipaddress; python_version < "3" (from cryptography>=1.5->paramiko)
  Downloading ipaddress-1.0.19.tar.gz
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko)
Building wheels for collected packages: ipaddress
  Running setup.py bdist_wheel for ipaddress ... done
  Stored in directory: /root/.cache/pip/wheels/d7/6b/69/666188e8101897abb2e115d408d139a372bdf6bfa7abb5aef5
Successfully built ipaddress
Installing collected packages: pyasn1, enum34, asn1crypto, idna, ipaddress, cryptography, pynacl, paramiko
Successfully installed asn1crypto-0.24.0 cryptography-2.1.4 enum34-1.1.6 idna-2.6 ipaddress-1.0.19 paramiko-2.4.0 pyasn1-0.4.2 pynacl-1.2.1"


but still get same error.

**Comment by m4rkw** [comment]
Ok, please bear with me while I recompile with a fix for this.

**Comment by stefanogalizia** [comment]
Sure, will wait

**Comment by m4rkw** [comment]
https://github.com/m4rkw/minotaur/releases/tag/v0.8.11

Please try that and let me know if it's still broken

**Comment by stefanogalizia** [comment]
Ok now it starts, i have to setup excavator now. 
thanks we can close this issue, if i have other problems i will open a new one.

**Comment by m4rkw** [comment]
cool glad its working, shout if you need any more help :)
