### ISSUE TITLE
Install/setup-script

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#5]
It would be nice to have an install script, that takes care of setting everything up on a fresh install of a Linux.

- Installing the correct NVIDIA drivers + required tools
- Installing minotaur/fanotaur/excavataur
- Setup minotaur as a service
etc.

Basically all the dirty work, that can be daunting for a (somewhat) newbie.

I have some experience installing and maintaining debian/ubuntu servers, but have no experience with nvidia drivers etc, so a script like this would be a really big help. 

I don't know if this is something you'd be interested in creating, but I'm sure it would give you more users.

What do you think?

**Comment by m4rkw** [comment]
yeah i'll get to it when i have time.  I have almost finished ansible code that does this, and plans to create a docker image to make it easier.  i just don't have much time unfortunately so the things that increase profits are taking priority over everything else

**Comment by biesbjerg** [comment]
Nice! 

Totally understandable. I'm installing Ubuntu and attempting to get everything going right now. If you have any pointers/gotchas they're appreciated!

Thank you for your work :)

**Comment by m4rkw** [comment]
we have a setup script for centos now: https://github.com/m4rkw/minotaur-install
