### ISSUE TITLE
GPU watchdog

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#9]
Sometimes GPUs drop out (too aggressive overclock or other sources of instabilities). 

I haven't been able to trace this anywhere in the logs. Would it be possible to create a log entry if a GPU drop out (preferably with info about core/mem clock speeds, temps, active miner and which GPU dropped out?).

If possible, also attempt one or all of the following:
- Reset crashed GPU (nvidia-smi --id=X --gpu-reset - not sure this is enough to recover a crashed gpu?)
- Reboot (if gpu-reset failed)

**Comment by m4rkw** [comment]
Typically when a GPU crashes it causes things like nvidia-smi etc to hang for long periods. I've not observed this happening on my system so I've no idea if it's possible to reset a card after a crash. I think rebooting the system in this event is outside the scope of what Minotaur should be doing, and is something that could be orchestrated with other scripts on the machine.

**Comment by m4rkw** [comment]
closing as i think orchestrating system events in the case of a GPU crash are outside the scope of minotaur
